version: '3.3'
services:
  cdash:
    image: "kitware/cdash"
    container_name: cdash
    depends_on:
      - postgres
      - selenium-hub
      - chrome
    links:
      - postgres
    ports:
     - "8080:80"
    environment:
      CDASH_ROOT_ADMIN_PASS: secret

      CDASH_STATIC_USERS: |
        USER jdoe@acme.com jdoe_secret
          John Doe "ACME Inc."

        ADMIN admin@example.org admin_secret
          Admin User "Example Foundation"

        donotreply@example.org oldsecret newsecret

        strange.name@gmail.com strange_secret
        INFO Str@nge N@me "Str@nge Rese@rch Gr0up LLC."

        DELETE remove.this.user@example.org delete_secret

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: root
      POSTGRES_DB: cdash4simpletest
  selenium-hub:
    image: selenium/hub:3.141.59-mercury
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-mercury
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
