services:
  cdash:
    environment:
      DB_CONNECTION: mysql
      DB_LOGIN: root
      DB_PORT: 3306

  database:
    image: mysql/mysql-server:5.7
    container_name: cdash_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_HOST: '%'
