version: '3.3'
services:
  cdash:
    image: "kitware/cdash:testing"
    container_name: cdash
    build:
      context: .
      dockerfile: ./docker/cdash.docker
      args:
        - CDASH_DB_HOST=postgres
        - DEVELOPMENT_BUILD=1
    depends_on:
      - postgres
      - selenium-hub
      - chrome
    links:
      - postgres
    ports:
     - "8080:80"
  postgres:
    image: postgres
    container_name: postgres_cdash
    environment:
      POSTGRES_PASSWORD: cdash4simpletest
  selenium-hub:
    image: selenium/hub:3.141.59-mercury
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-mercury
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
