- name: cdash-provisioner
  hosts: all

  roles:
    - role: geerlingguy.mysql
      sudo: yes
      mysql_databases:
        - name: cdash
        - name: cdash4simpletest
      mysql_users:
        - name: cdash
          password: cdash
          priv: "*.*:ALL"

    - role: geerlingguy.apache
      sudo: yes
      apache_vhosts:
        - {servername: localhost, documentroot: "{{ cdash_install_path }}/public"}

    - role: geerlingguy.php
      sudo: yes
      php_packages:
        - php5
        - php5-curl
        - php5-gd
        - php5-json
        - php5-mysql
        - php5-xdebug
        - php5-xsl
        - libapache2-mod-php5
      php_memory_limit: "512M"

    - role: geerlingguy.composer
      sudo: yes

    - role: leonidas.nvm
      sudo: yes
      nvm:
        user: vagrant
        version: v0.31.0
        node_version: v5.5.0

    - role: cdash
