kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-website
  labels:
    app: {{ .Release.Name }}-website
spec:
  ingressClassName: nginx
  {{ if .Values.cdash.https }}
  tls:
    - secretName: tls-cdash
  {{ end }}
  rules:
    - host: {{ .Values.cdash.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-website
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
